In [1]:
import pandas as pd
import numpy as np

import nltk
import spacy
import re
import string

from nltk.corpus import stopwords

In [2]:
resume_df = pd.read_csv(
    r"D:\AI_ATS_Resume_Screening_System\resume\test\csv\resume_data.csv"
)

resume_df.head()

,resume_name,resume_text,text_length,completeness_score
0,Abiral_Pandey_Fullstack_Java.pdf,Name: Abiral Pandey\nEmail: abiral.pandey88@gm...,13972,3
1,Anudeep N_Sr Java Developer.pdf,Anudeep\nSr Java Programmer\nanudeepreddynalla...,12049,4
2,Ashwini J2EE Developer.pdf,Ashwini C\n©732-352-1613\nashwinicha8@gmail.co...,19615,4
3,Bapuji Hadoop developer.pdf,Bapuji\nSr. Hadoop Developer\nPhone: +1(224)-7...,14384,4
4,CHETAN_Sr Java Developer.pdf,CHETAN BABU\nMobile: 405-896-0512\nEmail: boor...,13237,3

In [3]:
nlp = spacy.load("en_core_web_sm")

stop_words = set(stopwords.words('english'))

print("NLP resources loaded successfully!")

NLP resources loaded successfully!

In [4]:
print(resume_df["resume_text"][0][:3000])

Name: Abiral Pandey
Email: abiral.pandey88@gmail.com
Phone: 940-242-3303
Current Location: Woonsocket, Rhode Island
Visa Status: US Citizen
SUMMARY:
Dynamic individual with 6 years of software development experience in design, development,
deployment, maintenance, production and support of web - based and Client-Server business
applications using OOP and Java/J2EE technologies.
Exposure to all phases of Software Development Life Cycle(SDLC) using Agile, RUP, Waterfall.
Designed and developed web UI screen using Angular-JS.
Developed AngularJS Controllers, Services, filters and directives for various modules in the application.
Knowledge on ETL tools like Kettle Pentaho and Microsoft SSIS tools.
Created custom directives, decorators and services using AngularJS to interface with both RESTful
and legacy network services also DOM applications.
Experience with MVC frameworks like Struts, SPRING and ORM tools like Hibernate.
Experienced in working with batch jobs using Spring-Batch, Autosys and Quartz.
Worked extensively with XML related technologies like XML/XSLT to process, validate, parse and
extract data from XML using DOM and SAX parsers for DTD and SCHEMAand also worked
with JAX-B.
Strong experience in J2EE technologies like Java Beans, Servlets, JSP (including custom tags), JSTL,
JDBC, Struts, Spring, JMS, JNDI and Multithreading.
Expertise in web development technologies like HTML, DHTML, XHTML, CSS, Java Script, JQuery,
JSF, AJAX, Bootstrap JS, Node JS and Angular JS.
Experienced in RESTful web services using JAX-RS, Jersey framework and SOAP using JAX-WS,
Axis-2 framework.
Expert knowledge over J2EE Design Patterns like MVC, Adapter, Front End Controller, Value object,
Singleton, Session Facade, Business Delegate, Factory DAO in designing the architecture of large
applications.
Experience in using Maven and Ant build scripts for the project build automation.
Experience in using version control and configuration management tools like SVN, Clear
Case and CVS.
Expertise in working with various Application Servers such as IBM WebSphere, JBoss, Glassfish,
Oracle WebLogic and Apache Tomcat server.
Good knowledge in using IDE’s such as Eclipse, NetBeans, JBuilder, RAD and STS.
Expertise in working with Relational databases such as Oracle, PostgreSQL, DB2, MySQL and NoSQL
database MongoDB.
Experience in database design using PL/SQL to write Stored Procedures, Functions, Triggers,
views and good at writing complex queries for Oracle 10g/11g.
Good experience in developing test cases with JUnit for Unit testing, Load testing and logging
using Log4J.
Experienced in using Operating Systems like Windows 98 / 2000 / NT / XP, AIX, Sun Solaris.
Proficient in software documentation and technical report writing.
Involved in Performance analysis and improvements of the application using tools like Jmeter and
using commands on Unix box to resolve deadlocks and improve performance.
TECHNICAL SKILLS:
Programming Languages: Java/J2EE, PL/SQL, Unix Shell Scripts
Jav

In [5]:
def clean_resume_text(text):

    # Convert to string
    text = str(text)

    # Lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'http\S+', '', text)

    # Remove emails
    text = re.sub(r'\S+@\S+', '', text)

    # Remove phone numbers
    text = re.sub(r'\d{10,}', '', text)

    # Remove punctuation
    text = text.translate(
        str.maketrans('', '', string.punctuation)
    )

    # Remove numbers
    text = re.sub(r'\d+', '', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

In [6]:
resume_df["clean_text"] = resume_df["resume_text"].apply(
    clean_resume_text
)

resume_df.head()

,resume_name,resume_text,text_length,completeness_score,clean_text
0,Abiral_Pandey_Fullstack_Java.pdf,Name: Abiral Pandey\nEmail: abiral.pandey88@gm...,13972,3,name abiral pandey email phone current locatio...
1,Anudeep N_Sr Java Developer.pdf,Anudeep\nSr Java Programmer\nanudeepreddynalla...,12049,4,anudeep sr java programmer professional summar...
2,Ashwini J2EE Developer.pdf,Ashwini C\n©732-352-1613\nashwinicha8@gmail.co...,19615,4,ashwini c © sr javajee developer summary aroun...
3,Bapuji Hadoop developer.pdf,Bapuji\nSr. Hadoop Developer\nPhone: +1(224)-7...,14384,4,bapuji sr hadoop developer phone email profess...
4,CHETAN_Sr Java Developer.pdf,CHETAN BABU\nMobile: 405-896-0512\nEmail: boor...,13237,3,chetan babu mobile email professional summary ...

In [7]:
print("BEFORE:\n")
print(resume_df["resume_text"][0][:1000])

print("\n" + "="*100 + "\n")

print("AFTER:\n")
print(resume_df["clean_text"][0][:1000])

BEFORE:

Name: Abiral Pandey
Email: abiral.pandey88@gmail.com
Phone: 940-242-3303
Current Location: Woonsocket, Rhode Island
Visa Status: US Citizen
SUMMARY:
Dynamic individual with 6 years of software development experience in design, development,
deployment, maintenance, production and support of web - based and Client-Server business
applications using OOP and Java/J2EE technologies.
Exposure to all phases of Software Development Life Cycle(SDLC) using Agile, RUP, Waterfall.
Designed and developed web UI screen using Angular-JS.
Developed AngularJS Controllers, Services, filters and directives for various modules in the application.
Knowledge on ETL tools like Kettle Pentaho and Microsoft SSIS tools.
Created custom directives, decorators and services using AngularJS to interface with both RESTful
and legacy network services also DOM applications.
Experience with MVC frameworks like Struts, SPRING and ORM tools like Hibernate.
Experienced in working with batch jobs using Spring-Batch, Autosys

====================================================================================================

AFTER:

name abiral pandey email phone current location woonsocket rhode island visa status us citizen summary dynamic individual with years of software development experience in design development deployment maintenance production and support of web based and clientserver business applications using oop and javajee technologies exposure to all phases of software development life cyclesdlc using agile rup waterfall designed and developed web ui screen using angularjs developed angularjs controllers services filters and directives for various modules in the application knowledge on etl tools like kettle pentaho and microsoft ssis tools created custom directives decorators and services using angularjs to interface with both restful and legacy network services also dom applications experience with mvc frameworks like struts spring and orm tools like hibernate experienced in working with batch jobs using springbatch autosys and quartz worked extensively with xml related technologies like xmlxslt t

In [8]:
def remove_stopwords(text):

    words = text.split()

    filtered_words = [
        word
        for word in words
        if word not in stop_words
    ]

    return " ".join(filtered_words)

In [9]:
resume_df["clean_text"] = resume_df["clean_text"].apply(
    remove_stopwords
)

In [10]:
def lemmatize_text(text):

    doc = nlp(text)

    lemmas = []

    for token in doc:

        if not token.is_space:

            lemmas.append(token.lemma_)

    return " ".join(lemmas)

In [11]:
resume_df["clean_text"] = resume_df["clean_text"].apply(
    lemmatize_text
)

In [12]:
print("ORIGINAL:\n")
print(resume_df["resume_text"][0][:1000])

print("\n" + "="*100 + "\n")

print("CLEANED:\n")
print(resume_df["clean_text"][0][:1000])

ORIGINAL:

Name: Abiral Pandey
Email: abiral.pandey88@gmail.com
Phone: 940-242-3303
Current Location: Woonsocket, Rhode Island
Visa Status: US Citizen
SUMMARY:
Dynamic individual with 6 years of software development experience in design, development,
deployment, maintenance, production and support of web - based and Client-Server business
applications using OOP and Java/J2EE technologies.
Exposure to all phases of Software Development Life Cycle(SDLC) using Agile, RUP, Waterfall.
Designed and developed web UI screen using Angular-JS.
Developed AngularJS Controllers, Services, filters and directives for various modules in the application.
Knowledge on ETL tools like Kettle Pentaho and Microsoft SSIS tools.
Created custom directives, decorators and services using AngularJS to interface with both RESTful
and legacy network services also DOM applications.
Experience with MVC frameworks like Struts, SPRING and ORM tools like Hibernate.
Experienced in working with batch jobs using Spring-Batch, Autosys

====================================================================================================

CLEANED:

name abiral pandey email phone current location woonsocket rhode island visa status we citizen summary dynamic individual year software development experience design development deployment maintenance production support web base clientserver business application use oop javajee technology exposure phases software development life cyclesdlc use agile rup waterfall design develop web ui screen use angularjs develop angularjs controller service filter directive various module application knowledge etl tool like kettle pentaho microsoft ssis tool create custom directive decorator service use angularjs interface restful legacy network service also dom application experience mvc framework like strut spring orm tool like hibernate experience work batch job use springbatch autosys quartz work extensively xml relate technology like xmlxslt process validate parse extract data xml use dom sax parser dtd schemaand also work jaxb strong experience jee technology like java beans servlets jsp include

In [13]:
resume_df.to_csv(
    r"D:\AI_ATS_Resume_Screening_System\resume\test\csv\clean_resume_data.csv",
    index=False
)

print("Clean dataset saved successfully!")

Clean dataset saved successfully!

In [14]:
# to check todays work
resume_df["original_words"] = resume_df["resume_text"].apply(
    lambda x: len(str(x).split())
)

resume_df["clean_words"] = resume_df["clean_text"].apply(
    lambda x: len(str(x).split())
)

resume_df[
    [
        "resume_name",
        "original_words",
        "clean_words"
    ]
].head()

                        resume_name  original_words  clean_words
0  Abiral_Pandey_Fullstack_Java.pdf            1989         1568
1   Anudeep N_Sr Java Developer.pdf            1726         1325
2        Ashwini J2EE Developer.pdf            2736         2066
3       Bapuji Hadoop developer.pdf            2016         1546
4      CHETAN_Sr Java Developer.pdf            1848         1419